### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by amalic** [andygrove/rdbc#66]
Last commit was 13 months ago, and I can't find RDBC database drivers except the ones written by @andygrove.

**Comment by andygrove** [comment]
I wouldn't say "dead" but maybe comatose.

I, personally, am not actively working on this project because I am too busy with Ballista. There does seem to be a fair bit of interest in this project but I have not managed to encourage anyone to take the lead on contributing here. Perhaps you would be interested?

**Comment by aloucks** [comment]
The lack of `async` trait functions also presents some challenges, although there is an [issue](https://github.com/rust-lang/rfcs/issues/2739) to add them. The [`async_trait`](https://github.com/dtolnay/async-trait) macro may be useful in the meantime.

**Comment by amalic** [comment]
Thanks for the update
